### ISSUE TITLE
Use tslint instead of eslint

### ISSUE THREAD

**Issue by mentos1386** [troyedwardsjr/phaser3-typescript-webpack#3]
Currently there is used eslint and when running `npm run test` and checks for `.js` files. It should check for `.ts` files and use tslint.

Eslint is also missing as dependency.

https://github.com/troyedwardsjr/phaser3-typescript-webpack/blob/master/package.json#L11

**Comment by troyedwardsjr** [comment]
I choose to remove it because the primary benefit of linting is to enforce a specific style, usually for multiple developers working on the same project. I would rather not set up a default configuration and make this repository opinionated, as it seems unfitting and overly verbose when creating a boilerplate project which is friendly to new users.
